//////////////////////////////////
//          LOCALHOST           //
//////////////////////////////////
### Get all contacts
GET http://localhost:8080/contacts

### Get contact by ID
GET http://localhost:8080/contacts/687aa30e0fbc449862c7b106

### Create a new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "FirstName",
  "lastName": "LastName",
  "email": "email@ts.co",
  "favoriteColor": "Gray",
  "birthday": "01/20/3043"
}

### Update a contact by ID
PUT http://localhost:8080/contacts/696ffad198e6437cc8907dfc
Content-Type: application/json

{
  "firstName": "UpdatedFirstName",
  "lastName": "UpdatedLastName",
  "email": "updatedemail@ts.co",
  "favoriteColor": "Blue",
  "birthday": "01/20/3043"
}

### Delete a contact by ID
DELETE http://localhost:8080/contacts/696ffad198e6437cc8907dfc


//////////////////////////////////
//          PRODUCTION          //
//////////////////////////////////
### Get all contacts
GET https://get-contacts-api.onrender.com/contacts

### Get contact by ID
GET https://get-contacts-api.onrender.com/contacts/687aa30e0fbc449862c7b106

### Create a new contact
POST https://get-contacts-api.onrender.com/contacts/
Content-Type: application/json

{
  "firstName": "FirstName",
  "lastName": "LastName",
  "email": "email@ts.co",
  "favoriteColor": "Gray",
  "birthday": "01/20/3043"
}

### Update a contact by ID
PUT https://get-contacts-api.onrender.com/contacts/696fe3d269b8fc873516788c
Content-Type: application/json

{
  "firstName": "UpdatedFirstName",
  "lastName": "UpdatedLastName",
  "email": "updatedemail@ts.co",
  "favoriteColor": "Blue",
  "birthday": "01/20/3043"
}

### Delete a contact by ID
DELETE https://get-contacts-api.onrender.com/contacts/68827a09a7cd125bba8b3876
